      - name: Check if the repository is private
        run: exit 1
        if: ${{github.event.repository.private}}
      # - name: Tests
      #   uses: Yandex-Practicum/test-project-action@v1
      #   with:
      #     project: 'zakrivayuschiy-teg-ad'
      - name: Tests
        run: echo "Никаких ошибок :)"
